# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.9
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      -   id: flake8
  -   repo: https://github.com/timothycrosley/isort
      rev: '5.9.2'  # Use the revision sha / tag you want to point at
      hooks:
      - id: isort
        additional_dependencies: [toml]
